# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oneplus/onyx/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),onyx)

include $(CLEAR_VARS)
LOCAL_MODULE := libwpa_qmi_eap_proxy
LOCAL_MODULE_OWNER := oneplus
LOCAL_SRC_FILES := proprietary/vendor/lib/libwpa_qmi_eap_proxy.so
LOCAL_MULTILIB := 32
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_VENDOR_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libTimeService
LOCAL_MODULE_OWNER := oneplus
LOCAL_SRC_FILES := proprietary/vendor/lib/libTimeService.so
LOCAL_MULTILIB := 32
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_VENDOR_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libtime_genoff
LOCAL_MODULE_OWNER := oneplus
LOCAL_SRC_FILES := proprietary/vendor/lib/libtime_genoff.so
LOCAL_MULTILIB := 32
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_VENDOR_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := TimeService
LOCAL_MODULE_OWNER := oneplus
LOCAL_SRC_FILES := proprietary/vendor/app/TimeService/TimeService.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_VENDOR_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := shutdownlistener
LOCAL_MODULE_OWNER := oneplus
LOCAL_SRC_FILES := proprietary/vendor/app/shutdownlistener/shutdownlistener.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_VENDOR_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := qcrilmsgtunnel
LOCAL_MODULE_OWNER := oneplus
LOCAL_SRC_FILES := proprietary/priv-app/qcrilmsgtunnel/qcrilmsgtunnel.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ConnectivityExt
LOCAL_MODULE_OWNER := oneplus
LOCAL_SRC_FILES := proprietary/vendor/framework/ConnectivityExt.jar
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := .jar
LOCAL_VENDOR_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := qcnvitems
LOCAL_MODULE_OWNER := oneplus
LOCAL_SRC_FILES := proprietary/vendor/framework/qcnvitems.jar
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := .jar
LOCAL_VENDOR_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := qcrilhook
LOCAL_MODULE_OWNER := oneplus
LOCAL_SRC_FILES := proprietary/vendor/framework/qcrilhook.jar
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := .jar
LOCAL_VENDOR_MODULE := true
include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := OnePlusCamera
#LOCAL_MODULE_OWNER := oneplus
#LOCAL_SRC_FILES := proprietary/priv-app/OnePlusCamera/OnePlusCamera.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_PRIVILEGED_MODULE := true
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := OnePlusCameraService
#LOCAL_MODULE_OWNER := oneplus
#LOCAL_SRC_FILES := proprietary/priv-app/OnePlusCameraService/OnePlusCameraService.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_PRIVILEGED_MODULE := true
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := OnePlusGallery
#LOCAL_MODULE_OWNER := oneplus
#LOCAL_SRC_FILES := proprietary/priv-app/OnePlusGallery/OnePlusGallery.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_PRIVILEGED_MODULE := true
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := OnePlusWeather
#LOCAL_MODULE_OWNER := oneplus
#LOCAL_SRC_FILES := proprietary/priv-app/OnePlusWeather/OnePlusWeather.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_PRIVILEGED_MODULE := true
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := OnePlusWidget
#LOCAL_MODULE_OWNER := oneplus
#LOCAL_SRC_FILES := proprietary/priv-app/OnePlusWidget/OnePlusWidget.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_PRIVILEGED_MODULE := true
#include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Messaging
LOCAL_MODULE_OWNER := aosp
LOCAL_SRC_FILES := proprietary/priv-app/Messaging/Messaging.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := SGApps
LOCAL_MODULE_OWNER := aosp
LOCAL_SRC_FILES := proprietary/priv-app/SGApps/SGApps.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .apk
LOCAL_PRIVILEGED_MODULE := true
include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := wallhaven
#LOCAL_MODULE_OWNER := wallhaven.cc
#LOCAL_SRC_FILES := proprietary/priv-app/wallhaven/wallhaven.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_PRIVILEGED_MODULE := true
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := Musicolet
#LOCAL_MODULE_OWNER := Musicolet
#LOCAL_SRC_FILES := proprietary/priv-app/Musicolet/Musicolet.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_PRIVILEGED_MODULE := true
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := E-Aperture
#LOCAL_MODULE_OWNER := E-Aperture
#LOCAL_SRC_FILES := proprietary/priv-app/E-Aperture/E-Aperture.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_PRIVILEGED_MODULE := true
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := LightPainting
#LOCAL_MODULE_OWNER := LightPainting
#LOCAL_SRC_FILES := proprietary/priv-app/LightPainting/LightPainting.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_PRIVILEGED_MODULE := true
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := QPGallery
#LOCAL_MODULE_OWNER := QPGallery
#LOCAL_SRC_FILES := proprietary/priv-app/QPGallery/QPGallery.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_PRIVILEGED_MODULE := true
#include $(BUILD_PREBUILT)

endif
